Ikazuchi.Web/Areas/RtcSessions/Models/InviteAcceptForm.cs
namespace Ikazuchi.Web.Areas.RtcSessions.Models
{
    public class InviteAcceptForm
    {
    }
}

Ikazuchi.Web/Areas/RtcSessions/Models/InviteCreateForm.cs
using System;

namespace Ikazuchi.Web.Areas.RtcSessions.Models
{
    public class InviteCreateForm
    {
        public uint Expires { get; set; } = 60;

        public Guid SessionId { get; set; }
    }
}

Ikazuchi.Web/Areas/RtcSessions/Controllers/InviteController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Ikazuchi.Data;
using Ikazuchi.Data.Models.Users;
using Ikazuchi.Web.Areas.RtcSessions.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ikazuchi.Web.Areas.RtcSessions.Controllers
{
    [Area("RtcSessions")]
    [Authorize]
    public class InviteController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SessionGrantService _grantService;
        private readonly SessionInviteService _inviteService;
        private readonly UserManager<ApplicationUser> _userManager;

        public uint MaxInviteExpires = 72 * 60;

        public InviteController(
            SessionInviteService inviteService,
            SessionGrantService grantService,
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _inviteService = inviteService;
            _grantService = grantService;
            _context = context;
            _userManager = userManager;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] int expires, [FromForm] Guid sessionId)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return Unauthorized("You're not logged in");
            if (!await _grantService.Exists(sessionId, user.Id))
                return Unauthorized("You're not a member of this session");

            var session = await _context.RtcSessions.FirstOrDefaultAsync(s => s.Id == sessionId);
            if (session == null)
                return NotFound("Session not found");
            if (expires < 0 || expires > MaxInviteExpires)
                return BadRequest("Invalid expire time");

            var _ = await _inviteService.CreateAsync(session, user, (uint) expires);

            return RedirectToPage("/Details", new {area = "RtcSessions", id = sessionId});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromForm] uint inviteId)
        {
            // lookup invite
            var invite = await _context.RtcSessionInvites.FirstOrDefaultAsync(v => v.Id == inviteId);
            if (invite == null)
                return NotFound("Invite doesn't exist");

            // access control
            var user = await _userManager.GetUserAsync(User);
            if (invite.Creator != user)
                return Unauthorized("You don't own this invite link");

            invite.Disabled = true;
            await _context.SaveChangesAsync();

            return RedirectToPage("/Details", new {area = "RtcSessions", id = invite.Session.Id});
        }

        public async Task<IActionResult> Kick([FromForm] Guid sessionId, [FromForm] Guid userId)
        {
            var grant = await _context.RtcSessionGrants
                .Where(g => g.Session.Id == sessionId)
                .Where(g => g.User.Id == userId)
                .FirstOrDefaultAsync();

            if (grant == null)
                return NotFound("Grant not found");

            var user = await _userManager.GetUserAsync(User);
            if (user == null || user != grant.Session.Creator || user != grant.User)
                return Unauthorized();

            _context.RtcSessionGrants.Remove(grant);
            await _context.SaveChangesAsync();

            if (grant.Session.Creator == user)
                return RedirectToPage("/Details", new {area = "RtcSessions", id = grant.Session.Id});

            if (grant.User == user)
                return RedirectToPage("/Index", new {area = "RtcSessions"});

            throw new NotImplementedException("You shouldn't be there");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Join([FromForm] Guid sessionId)
        {
            var session = await _context.RtcSessions
                .Where(s => s.Id == sessionId)
                .FirstOrDefaultAsync();
            if (session == null)
                return NotFound();
            if (!session.Public)
                return Unauthorized();

            var user = await _userManager.GetUserAsync(User);
            await _grantService.Create(session, user);

            return RedirectToPage("/Details", new {area = "RtcSessions", id = sessionId});
        }
    }
}

Ikazuchi.Web/Areas/RtcSessions/Controllers/NavigationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Ikazuchi.Web.Areas.RtcSessions.Controllers
{
    [Area("RtcSessions")]
    public class NavigationController : Controller
    {
        public IActionResult Join()
        {
            return new EmptyResult();
        }
    }
}

Ikazuchi.Web/Areas/RtcSessions/Pages/Delete.cshtml.cs
using System;
using System.Threading.Tasks;
using Ikazuchi.Data;
using Ikazuchi.Data.Models.Rtc;
using Ikazuchi.Data.Models.Users;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Ikazuchi.Web.Areas.RtcSessions.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DeleteModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public RtcSession Session { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
                return NotFound();

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return Unauthorized();

            Session = await _context.RtcSessions.FirstOrDefaultAsync(m => m.Id == id);
            if (Session == null)
                return NotFound();

            if (Session.Creator != user)
                return Unauthorized();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
                return NotFound();

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return Unauthorized();

            Session = await _context.RtcSessions.FindAsync(id);
            if (Session == null)
                return NotFound();

            if (Session.Creator != user)
                return Unauthorized();

            Session.Deleted = true;
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Ikazuchi.Web/Areas/RtcSessions/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ikazuchi.Data;
using Ikazuchi.Data.Models.Rtc;
using Ikazuchi.Data.Models.Users;
using Ikazuchi.Web.Areas.RtcSessions.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Ikazuchi.Web.Areas.RtcSessions.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        private readonly SessionInviteService _inviteService;
        private readonly UserManager<ApplicationUser> _userManager;

        public DetailsModel(
            ApplicationDbContext context,
            SessionInviteService inviteService,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _inviteService = inviteService;
            _userManager = userManager;
        }

        public RtcSessionInvite ActiveInvite { get; set; }

        public IList<RtcSessionGrant> Grants { get; set; }

        public bool Joined { get; set; }

        public RtcSession Session { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null) return NotFound();

            Session = await _context.RtcSessions
                .Include(session => session.Creator)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Session == null) return NotFound();

            var user = await _userManager.GetUserAsync(User);

            // get active invite
            ActiveInvite = await _inviteService.GetActiveAsync(Session.Id, user.Id);

            // get all grants (members)
            Grants = await _context.RtcSessionGrants
                .OrderByDescending(grant => grant.CreationTime)
                .Where(grant => grant.Session.Id == Session.Id)
                .Include(grant => grant.User)
                .ToListAsync();

            Joined = Grants.Any(grant => grant.User == user);

            return Page();
        }
    }
}

Ikazuchi.Web/Areas/RtcSessions/Pages/Edit.cshtml.cs
using System;
using System.Threading.Tasks;
using Ikazuchi.Data;
using Ikazuchi.Data.Models.Rtc;
using Ikazuchi.Data.Models.Users;
using Ikazuchi.Web.Areas.RtcSessions.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Ikazuchi.Web.Areas.RtcSessions.Pages
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public EditModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public RtcSession Session { get; set; }

        [BindProperty] public SessionEditForm Form { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
                return NotFound();

            Session = await _context.RtcSessions
                .Include(t => t.Creator)
                .FirstOrDefaultAsync(t => t.Id == id);

            if (Session == null)
                return NotFound();

            if (Session.Creator != await _userManager.GetUserAsync(User))
                return Unauthorized();

            Form = new SessionEditForm
            {
                Description = Session.Description,
                Id = Session.Id,
                Title = Session.Title,
                Visibility = Session.Public ? SessionVisibility.Public : SessionVisibility.Private
            };

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
                return Page();

            var session = await _context.RtcSessions
                .Include(t => t.Creator)
                .FirstOrDefaultAsync(t => t.Id == Form.Id);

            if (session.Creator != await _userManager.GetUserAsync(User))
                // TODO: allow admin to edit
                return Unauthorized();

            session.Description = Form.Description;
            session.Public = Form.Visibility == SessionVisibility.Public;
            session.Title = Form.Title;

            await _context.SaveChangesAsync();

            return RedirectToPage("./Details", new {id = session.Id});
        }
    }
}

Ikazuchi.Web/Areas/RtcSessions/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ikazuchi.Data;
using Ikazuchi.Data.Models.Rtc;
using Microsoft.EntityFrameworkCore;

namespace Ikazuchi.Web.Areas.RtcSessions.Pages
{
    public class IndexModel : IndexModelBase
    {
        public IndexModel(ApplicationDbContext context) : base(context)
        {
        }

        public async Task OnGetAsync(int? pageIndex)
        {
            var query = Context.RtcSessions
                .Where(session => !session.Deleted)
                .Where(session => session.Public)
                .OrderByDescending(session => session.CreationTime);

            SessionCount = await query.CountAsync();
            if (SessionCount == 0)
            {
                Sessions = new List<RtcSession>();
                return;
            }

            PageCount = (int) Math.Ceiling((decimal) SessionCount / PageSize);
            PageIndex = Math.Clamp(1, pageIndex ?? 1, PageCount);

            Sessions = await query.Skip((PageIndex - 1) * PageSize).Take(PageSize).ToListAsync();
        }
    }
}

Ikazuchi.Web/Areas/RtcSessions/Pages/Init.cshtml.cs
using System;
using System.Threading.Tasks;
using Ikazuchi.Data;
using Ikazuchi.Data.Models.Rtc;
using Ikazuchi.Data.Models.Users;
using Ikazuchi.Web.Areas.RtcSessions.Models;
using Ikazuchi.Web.Areas.RtcSessions.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ikazuchi.Web.Areas.RtcSessions.Pages
{
    public class InitModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly SessionGrantService _grantService;

        private readonly UserManager<ApplicationUser> _userManager;

        public InitModel(
            ApplicationDbContext context,
            SessionGrantService grantService,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _grantService = grantService;
            _userManager = userManager;
        }

        [BindProperty] public SessionInitForm Form { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var currentUser = await _userManager.GetUserAsync(User);

            var sessionId = Guid.NewGuid();
            var entry = await _context.RtcSessions.AddAsync(new RtcSession
            {
                CreationTime = DateTime.Now,
                Creator = currentUser,
                Id = sessionId,
                Public = Form.Visibility == SessionVisibility.Public,

                Description = Form.Description,
                Title = Form.Title
            });

            await _context.SaveChangesAsync();

            await _grantService.Create(sessionId, currentUser.Id);

            return RedirectToPage("./Details", new {id = entry.Entity.Id});
        }
    }
}

Ikazuchi.Web/Areas/RtcSessions/Pages/Invite/Accept.cshtml.cs
using System.Threading.Tasks;
using Ikazuchi.Data;
using Ikazuchi.Data.Models.Rtc;
using Ikazuchi.Data.Models.Users;
using Ikazuchi.Web.Areas.RtcSessions.Services;
using Ikazuchi.Web.Common;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Ikazuchi.Web.Areas.RtcSessions.Pages.Invite
{
    public class AcceptModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly SessionGrantService _grantService;
        private readonly UserManager<ApplicationUser> _userManager;

        public AcceptModel(
            ApplicationDbContext context,
            SessionGrantService grantService,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _grantService = grantService;
            _userManager = userManager;
        }

        public RtcSessionInvite Invite { get; set; }

        public bool Joined { get; set; }

        public RtcSession Session { get; set; }

        public string Token { get; set; }

        public async Task<IActionResult> OnGet(string token)
        {
            if (token == null)
                return BadRequest("No invite token provided");

            Token = token;

            if (!Base58Encoding.TryDecode(token, out var bigId))
                return BadRequest("Invalid Invite Code Format");
            if (bigId <= 0 || bigId >= uint.MaxValue)
                return BadRequest("Invalid Invite Code Value");

            var invite = await _context.RtcSessionInvites
                .Include(v => v.Creator)
                .Include(v => v.Session)
                .FirstOrDefaultAsync(v => v.Id == (uint) bigId);

            if (invite == null)
                return NotFound();

            Invite = invite;
            Session = invite.Session;

            var user = await _userManager.GetUserAsync(User);
            Joined = user != null && await _grantService.Exists(invite.Session.Id, user.Id);

            return Page();
        }

        public async Task<IActionResult> OnPost(uint inviteId)
        {
            if (inviteId <= 0 || inviteId >= uint.MaxValue)
                return BadRequest("Invite Id out of range");

            var invite = await _context.RtcSessionInvites
                .FirstOrDefaultAsync(v => v.Id == inviteId);
            if (invite == null)
                return NotFound("Invite not found");

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return Unauthorized();

            await _grantService.Create(invite.Session, user);

            return RedirectToPage("/Details", new {area = "RtcSessions", id = invite.Session.Id});
        }
    }
}

Ikazuchi.Web/Areas/RtcSessions/Pages/Delete.cshtml
@page
@model Ikazuchi.Web.Areas.RtcSessions.Pages.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var creatorUser = Model.Session.Creator;
}

<h1 class="h2">Delete Session <small class="h6 text-muted">@Model.Session.Id</small></h1>

<h3>Are you sure you want to delete this?</h3>

<dl class="row">
    <dt class="col-sm-2">
        Created at
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Session.CreationTime)
    </dd>

    <dt class="col-sm-2">
        Created by
    </dt>
    <dd class="col-sm-10">
        @{
            var screenName = creatorUser.ScreenName;
            if (screenName == null || screenName.Trim().Equals(""))
            {
                screenName = creatorUser.UserName;
            }
        }
        @screenName &lt;@creatorUser.Email&gt;
    </dd>

    <dt class="col-sm-2">
        Visibility
    </dt>
    <dd class="col-sm-10">
        @if (Model.Session.Public)
        {
            <span class="badge badge-primary">Public</span>
        }
        else
        {
            <span class="badge badge-secondary">Private</span>
        }
    </dd>
</dl>

<form method="post">
    <button class="btn btn-danger">Delete</button>
    <a class="btn btn-outlink-dark" href="javascript:history.back();">Back</a>
</form>

Ikazuchi.Web/Areas/RtcSessions/Pages/Details.cshtml
@page
@using Ikazuchi.Data.Models.Users
@using Ikazuchi.Web.Areas.RtcSessions.Models
@using Ikazuchi.Web.Common
@using Microsoft.AspNetCore.Identity
@model Ikazuchi.Web.Areas.RtcSessions.Pages.DetailsModel
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var currentUser = await UserManager.GetUserAsync(User);
    var creatorUser = Model.Session.Creator;
}

@section Scripts
{
    <script src="~/js/InviteCreatePartial.js"></script>
}

<div class="jumbotron">
    <h1 class="display-4">@Html.DisplayFor(model => model.Session.Title)</h1>

    <dl class="row">
        <dt class="col-sm-2">
            Created at
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Session.CreationTime)
        </dd>

        <dt class="col-sm-2">
            Created by
        </dt>
        <dd class="col-sm-10">
            @{
                var screenName = creatorUser.ScreenName;
                if (screenName == null || screenName.Trim().Equals(""))
                {
                    screenName = creatorUser.UserName;
                }
            }
            @screenName &lt;@creatorUser.Email&gt;
        </dd>

        <dt class="col-sm-2">
            Visibility
        </dt>
        <dd class="col-sm-10">
            @if (Model.Session.Public)
            {
                <span class="badge badge-primary">Public</span>
            }
            else
            {
                <span class="badge badge-secondary">Private</span>
            }
        </dd>

        <dt class="col-sm-2 text-muted">
            Unique Id
        </dt>
        <dd class="col-sm-10 text-muted">
            <a asp-page="./Details" asp-route-id="@Model.Session.Id">@Html.DisplayFor(model => model.Session.Id)</a>
        </dd>
    </dl>

    <div>
        @if (Model.Joined)
        {
            <a class="btn btn-success" href="/Client?session=@Model.Session.Id" role="button">Connect</a>
        }
        else
        {
            <form method="post" asp-area="RtcSessions" asp-controller="Invite" asp-action="Join">
                <input type="hidden" name="sessionId" value="@Model.Session.Id"/>
                <button type="submit" class="btn btn-primary">Join</button>
            </form>
        }
        @if (creatorUser == currentUser)
        {
            // TODO: allow administrator to terminate
            <a asp-page="./Edit" asp-route-id="@Model.Session.Id" class="btn btn-secondary" role="button">Edit</a>
            <a class="btn btn-danger" asp-page="./Delete" asp-route-id="@Model.Session.Id" role="button">Delete</a>
        }
        <a asp-page="./Index" class="btn btn-outline-dark" role="button">Back to List</a>
    </div>

    <hr class="my-4">

    <p style="white-space: pre-wrap;">@Html.DisplayFor(model => model.Session.Description)</p>
</div>

@if (Model.Joined)
{
    <div>
        <h2 class="h4">Invite link</h2>
        @if (Model.ActiveInvite == null)
        {
            <!-- create new invite -->
            <form method="post" asp-controller="Invite" asp-action="Create">
                @{
                    var createInviteForm = new InviteCreateForm
                    {
                        Expires = 120,
                        SessionId = Model.Session.Id
                    };
                }

                <input type="hidden" asp-for="@createInviteForm.Expires" name="expires" id="ExpiresTotalMinute"/>
                <input type="hidden" asp-for="@createInviteForm.SessionId" name="sessionId"/>

                <div class="form-group row">
                    <span class="col-auto col-form-label">Expires in</span>

                    <input id="InviteExpireHour" class="col-sm-1 form-control" type="number" max="72" min="0"/>
                    <label for="InviteExpireHour" class="col-auto col-form-label">hours</label>

                    <input id="InviteExpireMinute" class="col-sm-1 form-control" type="number" max="60" min="0"/>
                    <label for="InviteExpireMinute" class="col-auto col-form-label">minutes</label>

                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        }
        else
        {
            <!-- show active invite -->
            <form method="post" asp-area="RtcSessions" asp-controller="Invite" asp-action="Delete">
                @{
                    var deleteInviteForm = new InviteDeleteForm
                    {
                        InviteId = Model.ActiveInvite.Id
                    };
                    var encodedInviteId = Base58Encoding.Encode(Model.ActiveInvite.Id);
                    var inviteUrl = Url.ActionLink("Accept", "Invite", new {token = encodedInviteId});
                }
                <div class="form-group row">
                    <input type="hidden" asp-for="@deleteInviteForm.InviteId" name="inviteId"/>

                    <a class="col-auto col-form-label" href="@inviteUrl">@inviteUrl</a>

                    <span class="col-auto col-form-label text-muted">
                        Expires in
                        <time class="time-ago" datetime="@Model.ActiveInvite.Expires">
                            @Html.DisplayFor(model => model.ActiveInvite.Expires)
                        </time>
                    </span>

                    <button type="submit" class="col-auto btn btn-danger">Delete</button>
                </div>
            </form>
        }
    </div>
}


<div class="table-responsive-lg">
    <h2 class="h4">Members</h2>

    <table class="table table-hover">
        @{
            var nameColumn = "col-3";
            var emailColumn = "col-4";
            var timeColumn = "col-3";
            var actionColumn = "col-1";
        }

        <thead>
        <tr class="d-flex">
            <td class="@nameColumn">Name</td>
            <td class="@emailColumn">Email</td>
            <td class="@timeColumn">Time Joined</td>
            <td class="@actionColumn"></td>
        </tr>
        </thead>

        <tbody>
        @foreach (var grant in Model.Grants)
        {
            <tr class="d-flex">
                @{
                    var hasScreenName = grant.User.ScreenName.Trim().Length > 0;
                    var grantScreenName = hasScreenName ? grant.User.ScreenName : grant.User.Email;
                }

                @if (hasScreenName || Model.Joined)
                {
                    <td class="@nameColumn">@grantScreenName</td>
                }
                else
                {
                    <td class="@nameColumn text-muted">Nameless</td>
                }

                @if (Model.Joined)
                {
                    <td class="@emailColumn">@grant.User.Email</td>
                }
                else
                {
                    <td class="@emailColumn text-muted">***</td>
                }

                <td class="@timeColumn">
                    <time class="time-ago" datetime="@grant.CreationTime">
                        @grant.CreationTime
                    </time>
                </td>

                <td class="@actionColumn">
                    @if (currentUser == creatorUser || currentUser == grant.User)
                    {
                        <form method="post" asp-controller="Invite" asp-action="Kick">
                            <input type="hidden" name="sessionId" value="@Model.Session.Id"/>
                            <input type="hidden" name="userId" value="@grant.User.Id"/>
                            <button class="btn btn-danger">
                                @if (currentUser == grant.User)
                                {
                                    @Html.Raw("Leave")
                                }
                                else
                                {
                                    @Html.Raw("Remove")
                                }
                            </button>
                        </form>
                    }
                </td>
            </tr>
        }
        </tbody>
    </table>

    <div class="alert alert-dark" role="alert">
        Users need to be a member of this session to see members&apos; Email.
    </div>
</div>

Ikazuchi.Web/Areas/RtcSessions/Pages/Edit.cshtml
@page
@using Ikazuchi.Web.Areas.RtcSessions.Models
@model Ikazuchi.Web.Areas.RtcSessions.Pages.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="h2">Edit Session <small class="h6 text-muted">@Model.Session.Id</small></h1>

<form method="post">
    <input type="hidden" asp-for="Form.Id"/>

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <!-- title -->
    <div class="form-group row">
        <label asp-for="Form.Title" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Form.Title" class="form-control"/>
            <span asp-validation-for="Form.Title" class="text-danger"></span>
        </div>
    </div>

    <!-- visibility -->
    <div class="form-group row">
        <label asp-for="Form.Visibility" class="col-sm-2 col-form-label"></label>

        <div class="col-sm-10">
            <div class="custom-control custom-control-inline custom-radio">
                @{
                    var publicButtonId = ViewData.TemplateInfo.GetFullHtmlFieldName("SessionVisibility_Public");
                }
                @Html.RadioButtonFor(model => model.Form.Visibility, SessionVisibility.Public, new
                {
                    @class = "custom-control-input",
                    id = publicButtonId
                })
                <label class="custom-control-label" for="@publicButtonId">Public</label>
            </div>

            <div class="custom-control custom-control-inline custom-radio">
                @{
                    var privateButtonId = ViewData.TemplateInfo.GetFullHtmlFieldName("SessionVisibility_Private");
                }
                @Html.RadioButtonFor(model => model.Form.Visibility, SessionVisibility.Private, new
                {
                    @class = "custom-control-input",
                    id = privateButtonId
                })
                <label class="custom-control-label" for="@privateButtonId">Private</label>
            </div>
        </div>
    </div>

    <hr/>

    <!-- description -->
    <div class="form-group">
        <label asp-for="Form.Description"></label>
        <textarea asp-for="Form.Description" class="form-control" type="text" rows="20"></textarea>
        <span asp-validation-for="Form.Description" class="text-danger"></span>
    </div>

    <!-- control buttons -->
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary"/>
        <a class="btn btn-secondary" role="button" asp-page="./Details" asp-route-id="@Model.Session.Id">Back</a>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}